In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('tiktok_dataset.csv')

In [4]:
df.head(10)

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,author_ban_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
0,1,claim,7017666017,59,someone shared with me that drone deliveries a...,not verified,under review,343296.0,19425.0,241.0,1.0,0.0
1,2,claim,4014381136,32,someone shared with me that there are more mic...,not verified,active,140877.0,77355.0,19034.0,1161.0,684.0
2,3,claim,9859838091,31,someone shared with me that american industria...,not verified,active,902185.0,97690.0,2858.0,833.0,329.0
3,4,claim,1866847991,25,someone shared with me that the metro of st. p...,not verified,active,437506.0,239954.0,34812.0,1234.0,584.0
4,5,claim,7105231098,19,someone shared with me that the number of busi...,not verified,active,56167.0,34987.0,4110.0,547.0,152.0
5,6,claim,8972200955,35,someone shared with me that gross domestic pro...,not verified,under review,336647.0,175546.0,62303.0,4293.0,1857.0
6,7,claim,4958886992,16,someone shared with me that elvis presley has ...,not verified,active,750345.0,486192.0,193911.0,8616.0,5446.0
7,8,claim,2270982263,41,someone shared with me that the best selling s...,not verified,active,547532.0,1072.0,50.0,22.0,11.0
8,9,claim,5235769692,50,someone shared with me that about half of the ...,not verified,active,24819.0,10160.0,1050.0,53.0,27.0
9,10,claim,4660861094,45,someone shared with me that it would take a 50...,verified,active,931587.0,171051.0,67739.0,4104.0,2540.0

In [5]:
df.describe()

,#,video_id,video_duration_sec,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count
count,19382.000000,1.938200e+04,19382.000000,19084.000000,19084.000000,19084.000000,19084.000000,19084.000000
mean,9691.500000,5.627454e+09,32.421732,254708.558688,84304.636030,16735.248323,1049.429627,349.312146
std,5595.245794,2.536440e+09,16.229967,322893.280814,133420.546814,32036.174350,2004.299894,799.638865
min,1.000000,1.234959e+09,5.000000,20.000000,0.000000,0.000000,0.000000,0.000000
25%,4846.250000,3.430417e+09,18.000000,4942.500000,810.750000,115.000000,7.000000,1.000000
50%,9691.500000,5.618664e+09,32.000000,9954.500000,3403.500000,717.000000,46.000000,9.000000
75%,14536.750000,7.843960e+09,47.000000,504327.000000,125020.000000,18222.000000,1156.250000,292.000000
max,19382.000000,9.999873e+09,60.000000,999817.000000,657830.000000,256130.000000,14994.000000,9599.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19382 entries, 0 to 19381
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   #                         19382 non-null  int64
 1   claim_status              19084 non-null  object
 2   video_id                  19382 non-null  int64
 3   video_duration_sec        19382 non-null  int64
 4   video_transcription_text  19084 non-null  object
 5   verified_status           19382 non-null  object
 6   author_ban_status         19382 non-null  object
 7   video_view_count          19084 non-null  float64
 8   video_like_count          19084 non-null  float64
 9   video_share_count         19084 non-null  float64
 10  video_download_count      19084 non-null  float64
 11  video_comment_count       19084 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 1.8+ MB

In [7]:
##Question 1: Each row represents a different claim that was filed about a video that needs to be reviewed.
##Question 2: Out of 12 columns, there are 3 integer types, 4 object types, and 5 float types. Any column without 19,382 nonnull entries will have null values. These are:
##claim status(object), video_transcription_text(object), and video_view_count, video_like_count, video_share_count, video_download_count, cideo_comment_count (all float).
##Question 3: There do seem to be some outliers in the video_view_count, video_like_count, and video_share_count. This conclusion is drawn simply by looking at the max value and
##looking at how large it is comapred to the 50% and 75% quartile. However, it also makes sense that if a video was flagged by users, this could be a reason why.

In [8]:
df['claim_status'].unique()

array(['claim', 'opinion', nan], dtype=object)

In [9]:
## Threre are three claim types (if counting nan)-> 'claim', 'opinion', 'nan

In [10]:
len(df[df['claim_status'] == 'claim'])

9608

In [11]:
len(df[df['claim_status'] == 'opinion'])

9476

In [12]:
len(df[df['claim_status'].isna()])

298

In [13]:
##The number of claim_status claims is 9608, the number of claim_satus opinion is 9476, and the nan value is 298. It is interesting that the claim value and the opinion value are almost
##identical

In [14]:
print(f'The average video view count for claim_status = "claim" is', str(df[df['claim_status'] == 'claim']['video_view_count'].mean().round(2)))
print(f'The median video view count for claim_status = "claim" is', str(df[df['claim_status'] == 'claim']['video_view_count'].median().round(2)))

The average video view count for claim_status = "claim" is 501029.45
The median video view count for claim_status = "claim" is 501555.0

In [15]:
print(f'The average video view count for claim_status = "opinion" is', str(df[df['claim_status'] == 'opinion']['video_view_count'].mean().round(2)))
print(f'The median video view count for claim_status = "opinion" is', str(df[df['claim_status'] == 'opinion']['video_view_count'].median().round(2)))

The average video view count for claim_status = "opinion" is 4956.43
The median video view count for claim_status = "opinion" is 4953.0

In [16]:
##Question 4: For the videos where the claim_status is a claim, as opposed to an opinion, viewership is just over 100x as much.

In [17]:
df['author_ban_status'].unique()

array(['under review', 'active', 'banned'], dtype=object)

In [18]:
df.groupby('claim_status')['author_ban_status'].value_counts()

claim_status  author_ban_status
claim         active               6566
              under review         1603
              banned               1439
opinion       active               8817
              under review          463
              banned                196
Name: count, dtype: int64

In [19]:
##Question: Threre are much much more ative opinion claims, however, the under review claims are approximatley 4x less and the number of banned authors is more than 10x less.

In [20]:
df.groupby('author_ban_status')['video_share_count'].median()

author_ban_status
active            437.0
banned          14468.0
under review     9444.0
Name: video_share_count, dtype: float64

In [21]:
##Question: Based on the median of video share count, there are almost 31x less active authors then there are banned authors

In [22]:
df.groupby('author_ban_status')[['video_share_count']].agg(['count','mean', 'median']).round(2)

                  video_share_count
                              count      mean   median
author_ban_status
active                        15383  14111.47    437.0
banned                         1635  29998.94  14468.0
under review                   2066  25774.70   9444.0

In [23]:
df.groupby('author_ban_status')[['video_view_count']].agg(['count','mean', 'median']).round(2)

                  video_view_count
                             count       mean    median
author_ban_status
active                       15383  215927.04    8616.0
banned                        1635  445845.44  448201.0
under review                  2066  392204.84  365245.5

In [24]:
df.groupby('author_ban_status')[['video_like_count']].agg(['count','mean', 'median']).round(2)

                  video_like_count
                             count       mean    median
author_ban_status
active                       15383   71036.53    2222.0
banned                        1635  153017.24  105573.0
under review                  2066  128718.05   71204.5

In [26]:
df.groupby(['claim_status','author_ban_status']).agg({'video_share_count': ['count','mean','median'], 'video_view_count': ['count','mean','median'],
                                                     'video_like_count': ['count','mean','median']})

                               video_share_count                         \
                                           count          mean   median
claim_status author_ban_status
claim        active                         6566  32769.101889  17774.5
             banned                         1439  34056.580959  19018.0
             under review                   1603  33155.623206  18084.0
opinion      active                         8817    217.166950    121.0
             banned                          196    208.423469    108.5
             under review                    463    220.431965    124.0

                               video_view_count                           \
                                          count           mean    median
claim_status author_ban_status
claim        active                        6566  499221.733171  499500.5
             banned                        1439  505907.917304  512572.0
             under review                  1603  504054.640674  500774.0
opinion      active                        8817    4958.120563    4958.0
             banned                         196    4876.530612    5083.5
             under review                   463    4958.105832    4884.0

                               video_like_count
                                          count           mean    median
claim_status author_ban_status
claim        active                        6566  164960.302924  121943.0
             banned                        1439  173719.102849  132044.0
             under review                  1603  165566.954460  125882.0
opinion      active                        8817    1091.714982     820.0
             banned                         196    1027.515306     799.5
             under review                   463    1139.663067     876.0

In [27]:
##Question: Based on the previous three tables created, the number of likes, views, and shares are greatly increased for baneed authors than active authors.

In [28]:
df['likes_per_view'] = (df['video_like_count']/df['video_view_count'])
df['comments_per_view'] = (df['video_comment_count']/df['video_view_count'])
df['shares_per_view'] = (df['video_share_count']/df['video_view_count'])
df.head()

,#,claim_status,video_id,video_duration_sec,video_transcription_text,verified_status,author_ban_status,video_view_count,video_like_count,video_share_count,video_download_count,video_comment_count,likes_per_view,comments_per_view,shares_per_view
0,1,claim,7017666017,59,someone shared with me that drone deliveries a...,not verified,under review,343296.0,19425.0,241.0,1.0,0.0,0.056584,0.000000,0.000702
1,2,claim,4014381136,32,someone shared with me that there are more mic...,not verified,active,140877.0,77355.0,19034.0,1161.0,684.0,0.549096,0.004855,0.135111
2,3,claim,9859838091,31,someone shared with me that american industria...,not verified,active,902185.0,97690.0,2858.0,833.0,329.0,0.108282,0.000365,0.003168
3,4,claim,1866847991,25,someone shared with me that the metro of st. p...,not verified,active,437506.0,239954.0,34812.0,1234.0,584.0,0.548459,0.001335,0.079569
4,5,claim,7105231098,19,someone shared with me that the number of busi...,not verified,active,56167.0,34987.0,4110.0,547.0,152.0,0.622910,0.002706,0.073175

In [29]:
df.groupby(['claim_status','author_ban_status']).agg({'likes_per_view': ['count', 'mean', 'median'], 
                                                      'comments_per_view': ['count', 'mean', 'median'], 'shares_per_view': ['count', 'mean', 'median']})

                               likes_per_view                      \
                                        count      mean    median
claim_status author_ban_status
claim        active                      6566  0.329542  0.326538
             banned                      1439  0.345071  0.358909
             under review                1603  0.327997  0.320867
opinion      active                      8817  0.219744  0.218330
             banned                       196  0.206868  0.198483
             under review                 463  0.226394  0.228051

                               comments_per_view                      \
                                           count      mean    median
claim_status author_ban_status
claim        active                         6566  0.001393  0.000776
             banned                         1439  0.001377  0.000746
             under review                   1603  0.001367  0.000789
opinion      active                         8817  0.000517  0.000252
             banned                          196  0.000434  0.000193
             under review                    463  0.000536  0.000293

                               shares_per_view
                                         count      mean    median
claim_status author_ban_status
claim        active                       6566  0.065456  0.049279
             banned                       1439  0.067893  0.051606
             under review                 1603  0.065733  0.049967
opinion      active                       8817  0.043729  0.032405
             banned                        196  0.040531  0.030728
             under review                  463  0.044472  0.035027

In [30]:
##Question: Claim rates and opinion differ greatly as across the board the claim rates seem to have the most amount of likes, shares, views, etc. However, these vides also have the
##greatest number of banned authors by a very large margin.